{
	"Version": "2012-10-17",
	"Id": "Policy1435295346197",
	"Statement": [
		{
			"Sid": "Stmt1435295095381",
			"Effect": "Allow",
			"Principal": "*",
			"Action": [
				"s3:DeleteObject",
				"s3:GetObject",
				"s3:PutObject"
			],
			"Resource": "arn:aws:s3:::cf-wildcard-plugin/*"
		},
		{
			"Sid": "Stmt1435295125392",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:ListBucket",
			"Resource": "arn:aws:s3:::cf-wildcard-plugin"
		}
	]
}